documentation 0https://plantuml.com/wbs-diagram
@startwbs
<style>
wbsDiagram {
  .async {
      BackgroundColor pink
  }
  .sync {
      BackgroundColor SkyBlue
  }
  .optional {
      LineStyle 9
  }
  .future {
      LineStyle 2
      LineThickness .5
      BackgroundColor White
  }
}
</style>

+ /
++ system
+++ start <<optional>>
++ Patient
++- ReadVSD
+++ Medication
++++ Medication Service
++++- EML Abruf <<async>>
+++++ EMP <<future>>
++++++ Add <<future>>
++++++ Remove <<future>>
++++++ Change <<future>>
++++- Query Consent Decision <<future>>
+++- Verschreibung <<future>>
++- EAU <<future>>
++ Actions
+++[#skyBlue] Action xyz (EMP Abruf)
++++[#skyBlue]  zb. Liste der Verschreibungen <<future>>

legend
    | Farbe | Bedeutung |
    | | Knoten (Keine Operation) |
    |<#skyBlue>| Synchron (direktes Ergebnis) |
    |<#pink>| Asynchron (generiert eine neue Aktion) |
    |<<future>>| Zukünftig angedacht |
end legend
@endwbs
